{% set name = "cmyt" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/yt-project/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 56be04bd80c688cea4d7a3f2481e4e3d4a4183b055e1674137ce1b0ba8105f20

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - hatchling
  run:
    - python
    - matplotlib-base >=3.8.0
    - numpy >=1.26.0,<3

test:
  source_files:
    - tests
  imports:
    - cmyt
    - cmyt.colormaps
  commands:
    - pip check
    - pytest -v
  requires:
    - pip
    - pytest
    - colorspacious

about:
  home: https://yt-project.org/
  summary: A collection of Matplotlib colormaps from the yt project
  description: |
    Matplotlib colormaps from the yt project!

    The following colormaps, as well as their respective reversed (*_r) versions are available:
      - Perceptually uniform sequential colormaps
      - Monochromatic sequential colormaps
      - Miscellaneous

  dev_url: https://github.com/yt-project/cmyt/
  doc_url: https://github.com/yt-project/cmyt/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
    - matthewturk
