{% set name = "cmyt" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmyt-{{ version }}.tar.gz
  sha256: cf308415401c615dffded3033be575373553573740298e44ef4b016ffd99a9be

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - hatchling
    - wheel
  run:
    - python
    - matplotlib-base >=3.8.0
    - numpy >=1.26.0,<3

test:
  imports:
    - cmyt
    - cmyt.colormaps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://yt-project.org/
  summary: A collection of Matplotlib colormaps from the yt project
  description: |
    Matplotlib colormaps from the yt project!

    The following colormaps, as well as their respective reversed (*_r) versions are available:
      - Perceptually uniform sequential colormaps
      - Monochromatic sequential colormaps
      - Miscellaneous

  dev_url: https://github.com/yt-project/cmyt/
  doc_url: https://github.com/yt-project/cmyt/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
    - matthewturk
