{% set name = "cmyt" %}
{% set version = "1.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmyt-{{ version }}.tar.gz
  sha256: be0262cb399e9492a13ad7ef4aeb45221665341a9c24438aa9955a39856f4f27

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - colorspacious >=1.1.2
    - matplotlib-base >=3.2.0
    - more-itertools >=8.4
    - numpy >=1.17.4
    - python

test:
  source_files:
    - tests/
  imports:
    - cmyt
    - cmyt.colormaps
  commands:
    - pip check
    - pytest tests -v
  requires:
    - pip
    - pytest

about:
  home: https://github.com/yt-project/yt
  summary: A collection of Matplotlib colormaps from the yt project
  description: |
    Matplotlib colormaps from the yt project!

    The following colormaps, as well as their respective reversed (*_r) versions are available:
      - Perceptually uniform sequential colormaps
      - Monochromatic sequential colormaps
      - Miscellaneous

  dev_url: https://github.com/yt-project/cmyt/
  doc_url: https://github.com/yt-project/cmyt/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
    - matthewturk
