{% set name = "cmyt" %}
{% set version = "1.0.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cmyt-{{ version }}.tar.gz
  sha256: 69a3a54ddca6c746f4ebb8dc1fe2078b0d968a3c737dd0377a55ad2100637411

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - colorspacious >=1.1.2
    - matplotlib-base >=2.1.0
    - more-itertools >=8.4
    - numpy >=1.13.3
    - python >=3.6
    - typing-extensions >=3.10.0.2

test:
  imports:
    - cmyt
    - cmyt.colormaps
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/yt-project/yt
  summary: A collection of Matplotlib colormaps from the yt project
  dev_url: https://github.com/yt-project/cmyt/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - neutrinoceros
    - matthewturk
